### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by grigio** [beinnova/lettore-umidita#1]
Ciao, potresti aggiungere il Dockerfile che hai usato per generare `beinnova/jsnight-demo`.
Tnx

**Comment by beinnova** [comment]
Ciao,
non ho usato il Dockerfile, mi sono sbattuto a manina :D

Giorgio

2015-05-09 19:55 GMT+02:00 Luigi Maselli notifications@github.com:

> Ciao, potresti aggiungere il Dockerfile che hai usato per generare
> beinnova/jsnight-demo.
> Tnx
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beinnova/lettore-umidita/issues/1.

## 

_Be__innova_ di _Giorgio Cerruti_
_WebSites | IT consultant | Web Developer_
_Phone: +39 340/87.68.326 :: Skype: beinnova_
_P.IVA: 10755560017_
_Visit Beinnova http://www.beinnova.it Site_
- Giorgio Cerruti
  http://it.linkedin.com/pub/giorgio-cerruti/31/422/852/
